version: "3"
services:
  db:
    image: postgres

  web:
    build: .
    command: python django_example/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_example
    ports:
      - "8000:8000"
    links:
        - db
